apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delete-ingress-rule
spec:
  ingressClassName: nginx
  rules:
   - host: todo-delete.abhaysingh.shop
     http:
       paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: delete-task-service
              port:
                number: 80


    